FROM rust:1.79-alpine AS builder
WORKDIR /usr/src/realm
COPY . .
RUN apk update && apk add \
        make \
        gcc \
        g++ \
        zlib \
        zlib-dev \
        ldc
RUN cargo build --release --features "mi-malloc"
FROM alpine:latest
COPY --from=builder /usr/src/realm/target/release/realm /usr/bin
RUN chmod +x /usr/bin/realm

ENTRYPOINT ["/usr/bin/realm"]